### PR TITLE
fix test race condition

### LINKED ISSUE #6: TestHasIsBloomCached failures
Moved from: https://github.com/ipfs/go-ipfs/issues/3208

```
--- FAIL: TestHasIsBloomCached (0.03s)
    bloom_cache_test.go:100: Bloom filter has cache miss rate of more than 5%
FAIL
FAIL    github.com/ipfs/go-ipfs/blocks/blockstore   0.053s
```

### PR DESCRIPTION
**Pull request by Stebalien**
Also stop exposing functions that don't do what they claim to do:

* Invalidate does, technically invalidate. However, it's not threadsafe.
* Rebuild doesn't *clear* the filter so it's only useful for the initial build.
  It's also not threadsafe.

We can restore these functions later if we need them (but we'll have to change a
few things to make them work properly).

Also adds a `Wait` function to allow waiting for the bloom filter to finish
building.

fixes #6

### CODE REVIEW

File: bloom_cache.go [hunk 1]
```diff
@@ -19,82 +20,95 @@ func bloomCached(ctx context.Context, bs Blockstore, bloomSize, hashCount int) (
...
 }
 
-func (b *bloomcache) Rebuild(ctx context.Context) {
-	evt := log.EventBegin(ctx, "bloomcache.Rebuild")
+func (b *bloomcache) Wait(ctx context.Context) error {
+	select {
+	case <-ctx.Done():
+		return ctx.Err()
+	case <-b.buildChan:
+		return b.buildErr
```
Comment (Stebalien) [inline bloom_cache.go]: This way we have a way of getting at these errors.

File: bloom_cache_test.go [hunk 2]
```diff
@@ -102,7 +98,7 @@ func TestHasIsBloomCached(t *testing.T) {
 	}
 
 	if float64(cacheFails)/float64(1000) > float64(0.05) {
-		t.Fatal("Bloom filter has cache miss rate of more than 5%")
+		t.Fatalf("Bloom filter has cache miss rate of more than 5%%")
```
Comment (Stebalien) [inline bloom_cache_test.go]: Go vet wasn't happy.

File: bloom_cache.go [hunk 3]
```diff
@@ -19,82 +20,95 @@ func bloomCached(ctx context.Context, bs Blockstore, bloomSize, hashCount int) (
...
 }
 
 type bloomcache struct {
-	bloom  *bloom.Bloom
 	active int32
 
-	// This chan is only used for testing to wait for bloom to enable
-	rebuildChan chan struct{}
-	blockstore  Blockstore
+	bloom    *bloom.Bloom
```
Comment (Stebalien) [inline bloom_cache.go]: Put the atomic first because go can be stupid about things like this.

File: bloom_cache.go [hunk 4]
```diff
@@ -19,82 +20,95 @@ func bloomCached(ctx context.Context, bs Blockstore, bloomSize, hashCount int) (
...
+	bc := &bloomcache{
+		blockstore: bs,
+		bloom:      bl,
+		hits: metrics.NewCtx(ctx, "bloom.hits_total",
+			"Number of cache hits in bloom cache").Counter(),
+		total: metrics.NewCtx(ctx, "bloom_total",
+			"Total number of requests to bloom cache").Counter(),
+		buildChan: make(chan struct{}),
+	}
+	go func() {
```
Comment (Stebalien) [inline bloom_cache.go]: Might as well do this all in one goroutine.
